//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIST
    {
        public ARTIST()
        {
            this.ARTIFACTs = new HashSet<ARTIFACT>();
        }
    
        public int ArtistId { get; set; }
        public string ArtistName { get; set; }
    
        public virtual ICollection<ARTIFACT> ARTIFACTs { get; set; }
    }
}
