//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIFACTPRESERVATION
    {
        public ARTIFACTPRESERVATION()
        {
            this.TESTUSEDs = new HashSet<TESTUSED>();
            this.TREATMENTREGIMENUSEDs = new HashSet<TREATMENTREGIMENUSED>();
            this.ARTIFACTs = new HashSet<ARTIFACT>();
        }
    
        public int ArtifactPreservationId { get; set; }
        public string Authenticated { get; set; }
        public string InitialCondition { get; set; }
    
        public virtual ICollection<TESTUSED> TESTUSEDs { get; set; }
        public virtual ICollection<TREATMENTREGIMENUSED> TREATMENTREGIMENUSEDs { get; set; }
        public virtual ICollection<ARTIFACT> ARTIFACTs { get; set; }
    }
}
