//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXHIBIT
    {
        public int ExhibitID { get; set; }
        public string ExhibitName { get; set; }
        public string ExhibitDescription { get; set; }
        public Nullable<System.DateTime> ExhibitBeginningDate { get; set; }
        public Nullable<System.DateTime> ExhibitEndingDate { get; set; }
        public int CollectionInExhibit { get; set; }
        public int LocationInExhibit { get; set; }
    
        public virtual COLLECTION COLLECTION { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual LOCATION LOCATION1 { get; set; }
    }
}
