//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOANEDLOG
    {
        public int LoanedArtifactID { get; set; }
        public int MuseumLoanedToID { get; set; }
        public System.DateTime DateLoaned { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
    }
}
