//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.EXHIBITs = new HashSet<EXHIBIT>();
            this.ARTIFACTs = new HashSet<ARTIFACT>();
            this.EXHIBITs1 = new HashSet<EXHIBIT>();
        }
    
        public int LocationId { get; set; }
        public int FloorNumber { get; set; }
        public int RoomNumber { get; set; }
        public string StorageOrDisplay { get; set; }
    
        public virtual ICollection<EXHIBIT> EXHIBITs { get; set; }
        public virtual ICollection<ARTIFACT> ARTIFACTs { get; set; }
        public virtual ICollection<EXHIBIT> EXHIBITs1 { get; set; }
    }
}
