//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        public TEST()
        {
            this.TESTUSEDs = new HashSet<TESTUSED>();
            this.TestTools = new HashSet<TestTool>();
            this.TREATMENTTECHNIQUEs = new HashSet<TREATMENTTECHNIQUE>();
        }
    
        public int TestId { get; set; }
        public string TestName { get; set; }
    
        public virtual ICollection<TESTUSED> TESTUSEDs { get; set; }
        public virtual ICollection<TestTool> TestTools { get; set; }
        public virtual ICollection<TREATMENTTECHNIQUE> TREATMENTTECHNIQUEs { get; set; }
    }
}
