//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTool
    {
        public TestTool()
        {
            this.TESTs = new HashSet<TEST>();
        }
    
        public int TestToolID { get; set; }
        public string TestToolName { get; set; }
    
        public virtual ICollection<TEST> TESTs { get; set; }
    }
}
