//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTUSED
    {
        public int TestId { get; set; }
        public int ArtifactPreservationId { get; set; }
        public System.DateTime TestDate { get; set; }
    
        public virtual ARTIFACTPRESERVATION ARTIFACTPRESERVATION { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
