//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATMENTTECHNIQUE
    {
        public TREATMENTTECHNIQUE()
        {
            this.TESTs = new HashSet<TEST>();
            this.TREATMENTREGIMEN = new HashSet<TREATMENTREGIMan>();
        }
    
        public int TreatementTechniqueId { get; set; }
        public string TechniqueName { get; set; }
        public string TechniqueDescription { get; set; }
    
        public virtual ICollection<TEST> TESTs { get; set; }
        public virtual ICollection<TREATMENTREGIMan> TREATMENTREGIMEN { get; set; }
    }
}
