//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATMENTREGIMENUSED
    {
        public int TreatmentRegimenId { get; set; }
        public int ArtifactPreservationId { get; set; }
        public System.DateTime TreatmentDate { get; set; }
    
        public virtual ARTIFACTPRESERVATION ARTIFACTPRESERVATION { get; set; }
        public virtual TREATMENTREGIMan TREATMENTREGIMan { get; set; }
    }
}
