//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artifact_Express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATMENTTOOL
    {
        public TREATMENTTOOL()
        {
            this.TREATMENTREGIMEN = new HashSet<TREATMENTREGIMan>();
        }
    
        public int ToolId { get; set; }
        public string ToolName { get; set; }
    
        public virtual ICollection<TREATMENTREGIMan> TREATMENTREGIMEN { get; set; }
    }
}
